package com.rogerguo.cymo.curve;

/**
 * @Description
 * @Date 6/4/20 8:38 PM
 * @Created by rogerguo
 */
public enum CurveType {
    Z_CURVE, Z_CURVE_TXY, HILBERT_CURVE, HILBERT_CURVE_TXY, CUSTOM_CURVE_XYTTXY, CUSTOM_CURVE_XYTXYT, CURVE_T1X7Y7,
    CURVE_X3Y3T8, CURVE_T1X3Y3, CURVE_X1Y1T8, CUSTOM_CURVE_XYT, CUSTOM_CURVE_TXY, CURVE_X1Y1T5, CURVE_X3Y3T5,
    CURVE_T5X7Y7, CURVE_X7Y7T8, CURVE_T1X4Y4, CURVE_TIME, CURVE_SPACE
}
